Add fragments from bottom navigation
IDolgopolov/Voice-It pull request #2
Opened 2020-11-01 20:36 UTC by siiena25

2020-11-02 11:55 UTC, IDolgopolov commented on app/src/main/java/com/com/technoparkproject/view/activities/MainActivity.java
> +        Typeface typeface = Typeface.createFromAsset(getAssets(), "font/Roboto-Medium.ttf");
стоит вынести в xml
android:fontFamily=""

2020-11-02 12:12 UTC, IDolgopolov requested changes

2020-11-02 12:12 UTC, denisdolgopolov commented on app/src/main/java/com/com/technoparkproject/view/activities/MainActivity.java
> +        getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container,
должна быть только одна точка, отвечающая за смену фрагментов
в нашем случае, стоит вызывать установку начально фрагмента через программный выбор пункта меню

bottomNavigation.setCheckedItem(R.id.nav_home) (или что-то подобное)

2020-11-02 12:12 UTC, IDolgopolov commented on app/src/main/java/com/com/technoparkproject/view/activities/MainActivity.java
> +            getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container,
Стоит проверять, не отображается ли этот фрагмент сейчас
Сценарии:
1. пользователь два раза кликнул на выбранный пункт меню
2. пересоздание активити -> bottomNavigation.select(R.id.nav_home) -> повторная замена и так отображенного фрагмента

Особенно большой проблемой это станет, если добавлять фрагменты в бек стек

replace() создает стек из фрагментов, даже если

2020-11-02 12:14 UTC, IDolgopolov requested changes

2020-11-02 12:14 UTC, IDolgopolov commented on app/src/main/java/com/com/technoparkproject/view/activities/MainActivity.java
> +        Typeface typeface = Typeface.createFromAsset(getAssets(), "font/Roboto-Medium.ttf");
Стоит вынести в xml
android:fontFamily=""

2020-11-14 17:04 UTC, IDolgopolov approved these changes

2020-11-14 17:04 UTC, merged